######################################################################
# Automatically generated by qmake (2.01a) lun. aot 29 06:06:47 2011
######################################################################

TEMPLATE = app
TARGET = 
TARGET = tabula_rasa
DEPENDPATH += . Algorithme Interface Ressources Algorithme/Pictogramme
INCLUDEPATH += . Interface Algorithme Algorithme/Pictogramme
CONFIG += debug
RC_FILE = iconSetter.rc
QT += xml svg printsupport widgets

target.path += /usr/bin/
INSTALLS += target
# Input
HEADERS += Algorithme/algorithmeScene.hpp \
           Algorithme/pictoBuilder.hpp \
           Interface/aboutDialog.hpp \
           Interface/mainwindow.hpp \
           Interface/resizeDialog.hpp \
           Interface/tabWidget.hpp \
           Algorithme/Pictogramme/ancreItem.hpp \
           Algorithme/Pictogramme/labelItem.hpp \
           Algorithme/Pictogramme/liaisonItem.hpp \
           Algorithme/Pictogramme/pictoAction.hpp \
           Algorithme/Pictogramme/pictoCondition.hpp \
           Algorithme/Pictogramme/pictoConditionMultiple.hpp \
           Algorithme/Pictogramme/pictogramme.hpp \
           Algorithme/Pictogramme/pictoIteration.hpp \
           Algorithme/Pictogramme/pictoProcedure.hpp \
           Algorithme/Pictogramme/pictoSortie.hpp \
    Interface/labeledit.hpp \
    Interface/sauvegarde.hpp \
    Algorithme/XML/PictoSortieParser.hpp \
    Algorithme/XML/PictoParser.hpp \
    Algorithme/XML/PictoProcedureParser.hpp \
    Algorithme/XML/PictoIterationParser.hpp \
    Algorithme/XML/PictoActionParser.hpp \
    Algorithme/XML/PictoConditionParser.hpp \
    Algorithme/XML/PictoConditionMultipleParser.hpp \
    Algorithme/Model/Algorithm.hpp
FORMS += Interface/aboutDialog.ui \
         Interface/mainwindow.ui \
         Interface/resizeDialog.ui \
    Interface/labeledit.ui \
    Interface/sauvegarde.ui
SOURCES += main.cpp \
           Algorithme/algorithmeScene.cpp \
           Algorithme/pictoBuilder.cpp \
           Interface/aboutDialog.cpp \
           Interface/mainwindow.cpp \
           Interface/resizeDialog.cpp \
           Interface/tabWidget.cpp \
           Algorithme/Pictogramme/ancreItem.cpp \
           Algorithme/Pictogramme/labelItem.cpp \
           Algorithme/Pictogramme/liaisonItem.cpp \
           Algorithme/Pictogramme/pictoAction.cpp \
           Algorithme/Pictogramme/pictoCondition.cpp \
           Algorithme/Pictogramme/pictoConditionMultiple.cpp \
           Algorithme/Pictogramme/pictogramme.cpp \
           Algorithme/Pictogramme/pictoIteration.cpp \
           Algorithme/Pictogramme/pictoProcedure.cpp \
           Algorithme/Pictogramme/pictoSortie.cpp \
    Interface/labeledit.cpp \
    Interface/sauvegarde.cpp \
    Algorithme/XML/PictoSortieParser.cpp \
    Algorithme/XML/PictoParser.cpp \
    Algorithme/XML/PictoProcedureParser.cpp \
    Algorithme/XML/PictoIterationParser.cpp \
    Algorithme/XML/PictoActionParser.cpp \
    Algorithme/XML/PictoConditionParser.cpp \
    Algorithme/XML/PictoConditionMultipleParser.cpp \
    Algorithme/Model/Algorithm.cpp
RESOURCES += Ressources/ressources.qrc






